node {
   def commit_id
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir("basics"){
       sh 'npm install --only=dev'
       sh 'npm test'
       }
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("ydekel/docker-nodejs-demo:${commit_id}", 'basics/').push()
     }
   }
   stage('docker run') {
     sh label: '', script: '''
      docker run --rm -tid --name docker_test -p 3000 ydekel/docker-nodejs-demo:latest
      docker kill docker_test
      
      '''
     }
   }

